previews:
  generation: automatic

# List all services *except* PostgreSQL databases here
services:
  # Django Web Service (API)
  - type: web
    runtime: python
    name: wastee-api
    repo: https://github.com/luluoliv/wastee-api # URL do repositório da API
    branch: main # ou a branch que você deseja implantar
    numInstances: 1
    region: oregon # ou outra região de sua escolha
    plan: standard  # ou outro plano que preferir
    buildCommand: pip install -r requirements.txt # Comando para instalar dependências
    startCommand: gunicorn app.wsgi:application --bind 0.0.0.0:8000 # Comando para iniciar o servidor
    autoDeploy: true # Se você quer implantações automáticas
    envVars:
      - key: DEBUG
        value: "false" # Mantenha como "false" em produção
      - key: SECRET_KEY
        generateValue: true # Gera uma chave secreta automaticamente
      - key: DATABASE_URL
        fromDatabase: # Referencia a propriedade de um banco de dados
          name: wastee-db
          property: connectionString
      - key: STRIPE_API_KEY
        sync: false 