# Generated by Django 4.2.1 on 2024-10-09 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('seller', 'Vendedor')], default='normal', max_length=10),
        ),
    ]
