# Generated by Django 4.2.1 on 2024-10-17 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_product_category_alter_product_seller_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='address',
        ),
        migrations.AddField(
            model_name='seller',
            name='birth_date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='seller',
            name='cpf',
            field=models.CharField(default=12345678900, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='rg',
            field=models.ImageField(default='seller_documents/rg/default.jpg', upload_to='seller_documents/rg/'),
        ),
        migrations.AddField(
            model_name='seller',
            name='selfie_document',
            field=models.ImageField(default='seller_documents/selfie/default.jpg', upload_to='seller_documents/selfie/'),
        ),
    ]
