# Generated by Django 4.2.1 on 2024-10-27 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_chat_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='participants',
        ),
    ]
