# Generated by Django 4.2.1 on 2024-10-31 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_comment_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='external_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
